apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manifests/deployment.yml
- manifests/service.yml
- manifests/namespace.yml

namespace: mattermost2discord

commonLabels:
  app.kubernetes.io/name: mattermost2discord

configMapGenerator:
- name: mm2disc-config
  literals:
  - PORT=3000
  - GIN_MODE=release

images:
- name: clubcedille/mattermost2discord
  newTag: v1.0.5
