<<<<<<< refs/remotes/origin/main
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manifests/deployment.yml
- manifests/service.yml
- manifests/namespace.yml

namespace: mattermost2discord

commonLabels:
  app.kubernetes.io/name: mattermost2discord

configMapGenerator:
- name: mm2disc-config
  literals:
  - PORT=3000
  - GIN_MODE=release

images:
- name: clubcedille/mattermost2discord
  newTag: v1.0.5
=======
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manifests/deployment.yml
- manifests/service.yml
- manifests/namespace.yml

namespace: mattermost2discord

commonLabels:
  app.kubernetes.io/name: mattermost2discord

configMapGenerator:
- name: mm2disc-config
  literals:
  - PORT=3000
  - GIN_MODE=release

secretGenerator:
- name: mm2disc-secrets
  literals:
  - DISCORD_TOKEN=<REPLACE_ME>
  - DISCORD_CHANNEL=<REPLACE_ME>
  - MATTERMOST_TOKEN=<REPLACE_ME>
  - TRIGGER_WORD_MATTERMOST=<REPLACE_ME>
>>>>>>> Update api/bot.go to fix invalid memory address error.
