@startuml Mattermost2Discord

'Diagram attributes
skinparam style strictuml
skinparam SequenceMessageAlignment center
skinparam sequence {
    ArrowColor DeepSkyBlue
    ActorBorderColor DeepSkyBlue
    LifeLineBorderColor blue
    LifeLineBackgroundColor #A9DCDF

    ParticipantBorderColor DeepSkyBlue
    ParticipantBackgroundColor DodgerBlue
    ParticipantFontName Impact
    ParticipantFontSize 17
    ParticipantFontColor #blue

    ActorBackgroundColor aqua
    ActorFontColor DeepSkyBlue
    ActorFontSize 17
    ActorFontName Aapex
}

actor User as User #WhiteSmoke
Participant Mattermost as MM #LightSteelBlue
Participant mm2disc as mm2disc #LightSteelBlue
Participant Discord as discord #LightSteelBlue

'Interactions sequences in order
mm2disc -[#SkyBlue]-> MM : Awaits for POST request
User -[#SkyBlue]> MM : Uses trigger word
MM -[#SkyBlue]> mm2disc : Sends POST request
mm2disc <-[#RoyalBlue]> MM : Reads request body
group Processing request body
    mm2disc -[#SkyBlue]-> mm2disc : Mattermost \nToken \nauthentification
    mm2disc -[#SkyBlue]-> mm2disc : Formating Mattermost \nuser message
end
mm2disc -[#SkyBlue]> discord : fowards message trough \ndiscord bot
@enduml