apiVersion: apps/v1
kind: Deployment
metadata:
  name: mattermost2discord
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    spec:
      containers:
      - name: mattermost2discord
        # Note: you should change this to a
        # specific version in your downstream
        # repository.
        image: clubcedille/mattermost2discord
        ports:
        - containerPort: 3000
          protocol: TCP
          name: http
        envFrom:
        - configMapRef:
            name: mm2disc-config
        - secretRef:
            name: mm2disc-secrets
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        resources:
          limits:
            cpu: '0.25'
            memory: 128Mi
          requests:
            cpu: '0.125'
            memory: 64Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
